name: Build, Release & Upload to VPS (Test)

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  build-release-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Generate new version tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          default_bump: minor

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          files: target/api.jar
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Rename JAR with version
        run: |
          mv target/api.jar target/api-${{ steps.tag.outputs.new_tag }}.jar

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -p 5680 -H 149.50.146.48 >> ~/.ssh/known_hosts

      - name: Ensure test directory exists
        run: |
          ssh -i ~/.ssh/id_rsa -p 5680 root@149.50.146.48 "mkdir -p /home/root/mis-proyectos/mi-app/test"

      - name: Remove old JAR from test
        run: |
          ssh -i ~/.ssh/id_rsa -p 5680 root@149.50.146.48 "rm -f /home/root/mis-proyectos/mi-app/test/*.jar"

      - name: Upload new .jar to test
        run: |
          scp -P 5680 -i ~/.ssh/id_rsa target/api-${{ steps.tag.outputs.new_tag }}.jar root@149.50.146.48:/home/root/mis-proyectos/mi-app/test/
