name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add known hosts
      run: |
        ssh-keyscan -p 5680 -H 149.50.146.48 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 5680 root@149.50.146.48 "
          # Verificar si el directorio 'mis-proyectos' existe, si no, crear el directorio
          echo 'Verificando si el directorio mis-proyectos existe';
          if [ ! -d '/home/root/mis-proyectos' ]; then
            echo 'Creando directorio mis-proyectos';
            mkdir -p /home/root/mis-proyectos;
          fi

          # Verificar si el directorio 'mi-app' existe, si no, crear el directorio y clonar el repositorio
          echo 'Verificando si el directorio mi-app existe';
          if [ ! -d '/home/root/mis-proyectos/mi-app' ]; then
            echo 'Creando directorio mi-app y clonando repositorio';
            mkdir -p /home/root/mis-proyectos/mi-app;
            cd /home/root/mis-proyectos/mi-app;
            git clone https://github.com/Nicovied0/api_deploy.git .;
          fi
          ls -la /home/root/mis-proyectos/mi-app

          # Cambiar al directorio del repositorio
          cd /home/root/mis-proyectos/mi-app;

          # Verificar si docker-compose.yml existe
          echo 'Verificando si docker-compose.yml existe';
          if [ -f 'docker-compose.yml' ]; then
            echo 'docker-compose.yml encontrado, ejecutando docker-compose';
            docker-compose up -d;
          else
            echo 'docker-compose.yml no encontrado en el directorio actual.';
            exit 1;
          fi
        "
